title: Adrian Kepka - adriankepka.pl
email: kepka.adrian@gmail.com
description: >-
    Adrian Kepka personal site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adriankepka.pl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Strus155
markdown: kramdown
show_excerpts: true
google_analytics: G-4GNX3F5XCN

remote_theme: thelehhman/plainwhite-jekyll

collections:
  posts:
    output: true
    permalink: /blog/:name
  drafts:
    output: false
    permalink: /draft/:name

plainwhite:
  name: Adrian Kepka
  tagline: Software Engineer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: Strus155
    github:  Strus
    linkedIn: in/akepka # format: locale/username

plugins:
  - jekyll-feed

