title: Adrian Kepka - adriankepka.pl
email: kepka.adrian@gmail.com
description: >-
    Adrian Kepka personal site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Strus155
github_username:  Strus
markdown: kramdown
show_excerpts: true

remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Adrian Kepka
  tagline: Senior Software Engineer
  tagline2: Technical Project Leader
  date_format: "%b %-d, %Y"

  social_links:
    twitter: Strus155
    github:  Strus
    linkedIn: in/akepka # format: locale/username

plugins:
  - jekyll-feed

